services:
  - type: web
    name: student-performance-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir app app:app
    healthCheckPath: /
    autoDeploy: true
